### ISSUE TITLE
MSVC2013 support?

### ISSUE THREAD

**Issue by rpavlik** [ericniebler/meta#23]
I know it's a long shot, since I see now newer versions use inline namespaces and constexpr, and I appreciate the desire to keep this lightweight, but it would be tremendously useful to be able to use this in VC2013 (which lacks at least those two things)

**Comment by rpavlik** [comment]
(or at least to be able to use portions, perhaps separating out parts of the header so I can just include the pieces I need)

**Comment by rpavlik** [comment]
This was as far as I got at the moment - still blows up the compiler. https://github.com/ericniebler/meta/compare/master...rpavlik:master

**Comment by rpavlik** [comment]
Hmm, even fails to build in VS2015 RC.

**Comment by gnzlbg** [comment]
VS2015 is not conforming to the C++11 standard yet. You can try to workaround the issues and if you post the error messages we _might_ be able to help. 

However, VS2015 lacks some C++11 features, like C++98's two-phase look-up, which cannot be easily worked around.

**Comment by ericniebler** [comment]
It would be a job and a half. VS is pretty broken wrt C++11. I would even be disinclined to accept a patch since then I need to maintain workarounds for it, and I prefer to spend my time elsewhere. If this is the route you want to go, I suggest you fork Meta and maintain your patch there.

**Comment by tamaskenez** [comment]
@rpavlik the [latest available VS compiler](http://webcompiler.cloudapp.net/) fails with different error messages than the VS2015RC. If you're planning to implement some workarounds you should wait until July 20th for the final version. Maybe there will be less workaround necessary,

**Comment by rpavlik** [comment]
Yeah, I wish MSVC had better standards support. Not sure it's worth the effort to try porting, since it seems at least 2015 final will be required for anything close to success. I just really appreciated the idea behind the blog post and was excited to find the code, with a license, maintained in a repo. Perhaps I'll be able to find an old, less-featureful revision to use that might serve my needs and keep me from writing yet-another-pseudo-MPL.

**Comment by porkybrain** [comment]
Allow me to shamelessly plug [brigand](https://github.com/edouarda/brigand) here ;) It provides much of the same functionality (with many of the ideas stolen from eric) but with support for MSVC2013

**Comment by ericniebler** [comment]
In a sense, the community has done itself and Microsoft a disservice by accommodating Microsoft's buggy compiler. MSVC will only get better if users complain. When popular libraries refuse to work around its serious and long-standing issues, MSVC will improve.

I can dream.

**Comment by gabyx** [comment]
Totally agree =), and to add: MSVC is just a pain for users with moderate C++ skill as well as for professionals when it comes to overcome stuff which is actually in the standard. However, most people anyway use some sort of unix env. on windows (how ironic is this) to eventually be able to compile (hand clapping) their clang/gcc compliant libraries...
