### ISSUE TITLE
Replace meta::eval with meta::_t, add meta::_v

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/meta#24]
I've long been bothered by meta's use of `eval` to do something as trivial as `typename T::type`. I would rather use `eval` to evaluate deferred expressions (currently achieved by doing a `let` without any argument bindings, which reads a bit awkwardly IMO). Besides, since meta doesn't trade in metafunctions the way MPL does, it's wrong to encourage users to think of accessing a nested type as "evaluating" anything.

Until recently, I couldn't think of a better name for the thing `eval` does. But how about this:

```c++
template <typename T>
using _t = typename T::type;

template <typename T>
constexpr typename T::type::value_type _v = T::type::value;
```

This introduces `_t` as fetching a nested `::type` and `_v` as fetching a nested `::value`. These are obviously intended to evoke the `xxx_t` and `xxx_v` traits and variable templates in `<type_traits>`.

@gnzlbg, thoughts?

**Comment by gnzlbg** [comment]
I agree that using `meta::eval` to access the nested type feels weird. I am not sure about the names `meta::_t` and `meta::_v` but I see the rationale behind them, they are short (which is good cause they are commonly used), and I don't have any better names right now. 

For `meta::_v` C++14 support is required.

**Comment by ericniebler** [comment]
I've added `meta::_t` and `meta::_v` but I haven't yet deprecated `meta::eval` (see 7ee4f97). I'd like to sit with this one a bit.

**Comment by mpark** [comment]
FWIW, I'm +1 on this.

**Comment by pfultz2** [comment]
I actually did something similar before(see [here](https://github.com/pfultz2/Zen/blob/zen11/zen/traits/transform.h)), but I found `eval` to be more familiar to people so I stopped using it. In general, I think it is a good idea, but it might be worth supporting both forms.

**Comment by ericniebler** [comment]
I've ripped out `eval`. The die is cast.
