### ISSUE TITLE
Something is wrong with the meta travis builds

### ISSUE THREAD

**Issue by gnzlbg** [ericniebler/meta#26]
Seems to be related to the biicode part of the travis.yml file in `after_success`. I guess it doesn't like being called by multiple jobs on each build. @Manu343726 could you take a look?

**Comment by Manu343726** [comment]
Of course.

**Comment by Manu343726** [comment]
Seems to be not biicode related. It looks like an weird error when trying to clean build artifacts: A lot of warnings raise during `git clean -df` command to prepare for bii deploy. I will submit an issue to travis guys asking for feedback.

**Comment by gnzlbg** [comment]
This is how it looked before: https://travis-ci.org/ericniebler/meta/builds/69597163#L570

**Comment by Manu343726** [comment]
Is that the latest successful build?

**Comment by gnzlbg** [comment]
Yes. 

The PR build was fine, see [here](https://travis-ci.org/ericniebler/meta/jobs/70040972#L730). In the raw log however, it finishes fine. 

In the current build, the raw log says at the end that `git clean -df finished`, but:

```shell
travis_time:end:03004b03:start=1436522107387629122,finish=1436522109607647729,duration=2220018607
[0Ktravis_fold:end:after_success.3
[0Ktravis_fold:start:after_success.4
[0Ktravis_time:start:1ae3d0a4
[0K$ bii init -l
[32mSuccessfully initialized biicode project [0m
[0mtravis_time:end:1ae3d0a4:start=1436522109614835966,finish=1436522111170966689,duration=1556130723
[0Ktravis_fold:end:after_success.4
[0Ktravis_fold:start:after_success.5
[0Ktravis_time:start:0ccfa6be
[0K$ bii user $BIICODE_USER -p $BIICODE_PASSWORD
INFO: Change user from None to ericniebler [0m
[0mtravis_time:end:0ccfa6be:start=1436522111178814864,finish=1436522112799407783,duration=1620592919
[0Ktravis_fold:end:after_success.5
[0Ktravis_fold:start:after_success.6
[0Ktravis_time:start:25e9b382
[0K$ if [ -n "$BIICODE_PASSWORD" ]; then bii publish -r; fi
[1m[33m[40mWARN: Discarding 'git://github.com/ericniebler/meta.git' origin. Pending changes not pushed![0m
INFO: Input origin info:[0m
[32mUrl: [0m
```

This is was I assumed that it was biicode related. The `bii publish -r` command stalls for 10 mins.

**Comment by Manu343726** [comment]
I think I got it: `bii publish -r` command calls `git` to add versioning info to the deploy, ao you can see to what commit corresponds your latest "release" available at bii cloud. Seems like the repo is in an invalid state (Maybe the reason for the warnings during clean) so that internal call to git asking for info fails. When this happens bii asks user to enter git remote info manually. That's why the build hangs (Note the last line from the log, 32m waiting for "Url:" input).

[This](https://github.com/biicode/client/blob/d23a8371b78e9716f375715f1147b2c212687193/shell/origin_manager.py#L38) is the function that requests git info, called from [`bii publish`](https://github.com/biicode/client/blob/d23a8371b78e9716f375715f1147b2c212687193/command/biicommand.py#L229) through [this function](https://github.com/biicode/client/blob/d23a8371b78e9716f375715f1147b2c212687193/command/biicommand.py#L258) when `-r` option is passed. The latest function I linked is which asks for user input if git command fails, where the build is locked.

Hopefully (for me xD) this is not bii related but something weird happening with the git repo state. I will continue looking to find the problem.

**Comment by gnzlbg** [comment]
The last build broke with some git related issues:

https://travis-ci.org/ericniebler/meta/builds/70091012

Maybe that is the reason?

**Comment by ericniebler** [comment]
> The last build broke with some git related issues:
> https://travis-ci.org/ericniebler/meta/builds/70091012

I've seen that before. It's intermittent and has never causes lasting trouble.

**Comment by ldionne** [comment]
Did you guys rebase the doc/gh-pages branch? This problem usually happens to me when I push a feature branch to Travis for testing, then remove that branch after merging to master, and then try to replay the Travis build.

**Comment by Manu343726** [comment]
> The last build broke with some git related issues:
> https://travis-ci.org/ericniebler/meta/builds/70091012

This happened to me yesterday too after updating my fork to work on this. See https://travis-ci.org/Manu343726/meta/jobs/70441741

I'm writing an issue to travis-ci repo.

**Comment by ericniebler** [comment]
Would merging a squashed PR cause this?

**Comment by ldionne** [comment]
> Would merging a squashed PR cause this?

I don't think so. The situation I was talking about requires modifying public history, which you didn't do.

**Comment by Manu343726** [comment]
Maybe we should encourage Travis team to talk here, they dropped some feedback at the issue above.

**Comment by ericniebler** [comment]
Oh man. This was user error. [My bad](https://github.com/travis-ci/travis-ci/issues/4294#issuecomment-120654660).

**Comment by ericniebler** [comment]
Now there is a problem with clang-3.4 on travis. @gnzlbg any thoughts?

**Comment by ericniebler** [comment]
TODO: figure out what's going on with clang-3.4 on travis.

**Comment by ldionne** [comment]
FWIW, you may want to cherry-pick from [Hana's .travis.yml](https://github.com/ldionne/hana/blob/e0b56a3d187447a870cd2a4d7246f07d7baa3e2f/.travis.yml). It builds with Clang 3.{5,6,7} with libc++ and libstdc++. And it's on the new container-based Travis architecture. It should be pretty trivial to add Clang 3.4 to it for Meta.

**Comment by gnzlbg** [comment]
Thanks @ldionne , gonna move meta to the new container-based architecture and see if it solves the problem. Clang 3.7 is also failing for no apparent reason (while for range-v3 it works fine).

**Comment by ericniebler** [comment]
If nobody has time to look at this (not blaming anybody, time is a scarce commodity), I'll disable travis and biicode integration.

**Comment by Manu343726** [comment]
Disable biicode deploy if you like, just to be sure the issues are not related to bii. Also this would clear a bit travis builds output.
