### ISSUE TITLE
Namespace collision

### ISSUE THREAD

**Issue by pawelswoboda** [ericniebler/meta#36]
When using meta and curses together, a name collision occurs, as there is a function called meta in curses, see http://linux.die.net/man/3/meta

**Comment by gnzlbg** [comment]
I don't know of any good standard way of solving this problem. The two following workarounds "work" but are ugly:

```c++
namespace linux {
#include <ncurses.h>
}  // namespace linux
using linux::max_align_t;  // ncurses assumes it is in the global namespace
#include <meta/meta.hpp>
```

or 

```c++
#include <ncurses.h>
namespace cpp {
#include <meta/meta.hpp>
}  // namespace cpp
```

and in particular the second workaround will definetely break if `meta` internally assumes that the meta namespace is in the global namespace.

**Comment by gnzlbg** [comment]
So I've asked this on SO: http://stackoverflow.com/questions/37393414/name-collision-between-c-library-namespace-and-c-linux-function

Seems that your best bet is to use the `ncurses` c++ bindings. If they are not shipped by your distribution they should be inside the `ncurses` source directory.
