### ISSUE TITLE
clang 10.0 compiler error

### ISSUE THREAD

**Issue by gabyx** [ericniebler/meta#77]
I get a compile error with clang 10.0:

```
meta/meta_fwd.hpp:286:20: error: expected concept name with optional arguments
[build]         { T{} } -> typename T::value_type;
[build]                    ^
```
Whats the fix?

**Comment by b1ackviking** [comment]
I am experiencing the same error on GCC 11 with `-std=c++20`.

**Comment by ericniebler** [comment]
Ah, should be something like `{ T{} } -> convertible_to<typename T::value_type>`.

The concepts language feature changed between the Concepts TS and C++20.
